// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { GoogleOAuthProvider } from '@react-oauth/google';
// import  { Toaster } from 'react-hot-toast';
// import "./globals.css";
// import { Inter } from 'next/font/google'
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// const inter = Inter({ subsets: ["latin"] });
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable}   ${geistMono.variable} h-full antialiased`}
//     >
//       {/* 598712780231-hs2ekjg5672jjgm2l76i5s49mcplhfnj.apps.googleusercontent.com */}
//       {/* 598712780231-hs2ekjg5672jjgm2l76i5s49mcplhfnj.apps.googleusercontent.com */}
//       <GoogleOAuthProvider clientId="598712780231-hs2ekjg5672jjgm2l76i5s49mcplhfnj.apps.googleusercontent.com">
//       <body className="min-h-full flex flex-col">{children}</body>
//       <Toaster/>
//       </GoogleOAuthProvider>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Inter } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <GoogleOAuthProvider clientId="598712780231-hs2ekjg5672jjgm2l76i5s49mcplhfnj.apps.googleusercontent.com">

          {children}

          <Toaster position="top-right" />

        </GoogleOAuthProvider>

      </body>
    </html>
  );
}