// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // url: process.env["DATABASE_URL"],
    url:process.env["postgresql://postgres.cglksygphitdezmlntwr:FMgstySe46xC0aVG@aws-1-ap-south-1.pooler.supabase.com:5432/postgres?pgbouncer=true"]
  },
});
